version: '3'

services:
  frontend:
    build: /frontend
    restart: always
    container_name: frontend
    ports:
      - '6001:6001'
    command: 'npm run start'
  nginx:
    build: /nginx
    container_name: proxy_nginx
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./logs:/var/log/nginx/
    depends_on:
      - frontend
