version: '3'
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    restart: always
    container_name: frontend
    ports:
      - '6001:6001'
    command:
      'npm run start'
  nginx:
    build:
      context: ./nginx
      dockerfile: ./Dockerfile
    container_name: proxy_nginx
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./logs:/var/log/nginx/
    depends_on:
      - frontend
    command:
      'nginx -g "daemon off;"'