version: '3.7'

services:
  nginx:
    build: ./nginx
    container_name: proxy_nginx
    ports:
      - '80:80'
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./logs:/var/log/nginx/
    depends_on:
      - frontend
  frontend:
    build: ./frontend
    restart: always
    container_name: frontend
    ports:
      - '6001:6001'
    command: 'npm run start'
