version: '3'
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: ./frontend/Dockerfile
    restart: always
    container_name: frontend
    ports:
      - '3000:3000'
    command:
      'npm run start'