version: '3'
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    restart: always
    container_name: frontend
    ports:
      - '3000:3000'
    command:
      'npm run start'
  nginx:
    image: nginx:1.20
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./logs:/var/log/nginx/
    depends_on:
      - frontend